### ISSUE TITLE
Be able to set deployment replicas amount

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-framework#436]
By default, a deployment is set to just a single replica

```
 spec:
    replicas: 1
    selector:
      deploymentconfig: "${SERVICE_NAME}"
    template:
      metadata:
        labels:
          deploymentconfig: "${SERVICE_NAME}"

```

In some scenarios would be useful to be able to set the number of replicas by a test.property configuration

`ts.<your_service_name>.openshift.replicas=10`
